### ISSUE TITLE
Configure storage

### ISSUE THREAD

**Issue by erikkrieg** [erikkrieg/eksys#11]
My first pass at installing NixOS does not have a thoroughly considered approach to storage partitions. There are some questions, concerns and undone tasks that should be addressed.

**Tasks:**

- [ ] Potentially create `/nix` partition.
- [ ] Disk drive (1TB) needs to be partitioned. What should go there? `/home`?
- [ ] Consider garbage collection strategy.

### Create `/nix` partition
- I have seen `noatime` option mentioned for this partition. What does it do? Should I use it, too?
- What are the implications of different `fsType` for this partition?

## References
- https://nixos.wiki/wiki/Storage_optimization
